import 'package:flutter/material.dart';

const String routeLogin = '/login';
const String routeHome = '/';
const String routeFilter = '/filter';
const String routeBuilder = '/builder';
const String routeBuilderList = '/builder-list';
const String routeProfile = '/profile';
const String routeExotic = '/exotic';
const String routeCollection = '/collection';
const String routeInspect = "/inspect";
const String routeChangeSubclass = "/change-subclass";
const String routeInspectMobile = "/inspect-mobile-weapon";
const String routeInspectMobileArmor = "/inspect-mobile-armor";
const String routeSubclass = "/subclass";
const String routeSubclassMod = "/subclass-mod";
const String routeMod = "/mod";
const String routeBuilderRecap = "/builder-recap";
const String routeClassItemChoice = "/class-item-choice";
const String routeVault = "/vault";
const String routeInspectSubclass = "/inspect-subclass";
const String routeCollectionItem = "/collection-item";
const String routePageSettings = "/settings";
const String routePageLegends = "/legends";
const String routeCreateBuild = "/create-build";
const String routeListBuilds = "/list-builds";
const String routeDetailsBuild = "/details-build";
const String routeForeignBuild = "/foreign-build";

final navKey = GlobalKey<NavigatorState>();
